// Kit-owned guide content (skills, playbooks, principles, flows). Mirrors .agents/skills/**.
// Project-specific content (name, verify ladder) lives in docs/agents/guide.js, loaded after this.
// After any change under .agents/, .cursor/agents/ or docs/agents/: bash .agents/loop-guide/build.sh
window.PROJECT = { name: 'this project' };
window.STAGES = [
  { id: 'entry', label: 'Entry', color: '#f5b84b' },
  { id: 'align', label: 'Align', color: '#7aa2ff' },
  { id: 'plan', label: 'Plan', color: '#b38cff' },
  { id: 'understand', label: 'Understand & design', color: '#4fd1c5' },
  { id: 'build', label: 'Build', color: '#68d391' },
  { id: 'ship', label: 'Review & ship', color: '#f6874b' },
  { id: 'session', label: 'Session hygiene', color: '#a0aec0' },
];

// who: 'you' = user-invoked (disable-model-invocation), 'agent' = agent can reach for it too.
// calls: skills this one explicitly loads.
window.SKILLS = {
  'almalgo-mode': { stage: 'entry', who: 'you', src: 'New, on the pstack pattern',
    what: 'The front door. Sizes the task, picks one of 9 playbooks, applies the team principles, proves the work with verify.md, and always finishes with code-review then pr. A change to .agents/ also rebuilds this guide.',
    when: 'Any non-trivial task. In Cursor, Alt+Enter keeps it on for the whole session (Custom Mode).',
    io: 'Reads AGENTS.md (root + area), GLOSSARY.md, docs/adr, docs/agents/verify.md. Turns the playbook steps into your todo list.',
    calls: ['how', 'why', 'architect', 'diagnosing-bugs', 'tdd', 'prototype', 'code-review', 'pr', 'grill-with-docs', 'to-spec', 'to-tickets', 'wayfinder', 'handoff', 'codebase-design', 'writing-for-agents'] },

  'setup-almalgo-mode': { stage: 'entry', who: 'you', src: 'New, from mattpocock setup',
    what: 'One-time setup after install.sh. Explores the repo, then writes the project-owned docs/agents/ files: the verify ladder, guide data, issue tracker, triage labels, domain docs. Adds the AGENTS.md section and builds this guide.',
    when: 'Right after installing the kit in a repo, or to re-check a half-finished setup.',
    io: 'Writes docs/agents/*, edits AGENTS.md. Offers to create missing labels (asks first).', calls: [] },

  'grill-me': { stage: 'align', who: 'you', src: 'mattpocock/skills',
    what: 'Relentless interview about a plan until every branch of the design tree is resolved.',
    when: 'Any plan or decision, code or not.', io: 'Conversation only.', calls: ['grilling'] },
  'grill-with-docs': { stage: 'align', who: 'you', src: 'mattpocock/skills',
    what: 'Same interview, plus it writes GLOSSARY.md terms and ADRs the moment they are decided.',
    when: 'Start of every big or ambiguous change. The first step of the big-work path.',
    io: 'Writes GLOSSARY.md and docs/adr/NNNN-*.md.', calls: ['grilling', 'domain-modeling'] },
  'grilling': { stage: 'align', who: 'agent', src: 'mattpocock/skills',
    what: 'The interview primitive. Asks the whole frontier of answerable questions per round, numbered, each with a recommended answer.',
    when: 'Reached for by grill-me, grill-with-docs, triage, wayfinder, improve-codebase-architecture.', io: 'Conversation only.', calls: [] },
  'domain-modeling': { stage: 'align', who: 'agent', src: 'mattpocock/skills',
    what: 'Challenges terms against the glossary, invents edge cases, writes entries. Writes an ADR only when a decision is hard to reverse, surprising, and a real trade-off.',
    when: 'Whenever terminology or a lasting decision is being settled.', io: 'GLOSSARY.md, docs/adr/.', calls: [] },
  'triage': { stage: 'align', who: 'you', src: 'mattpocock/skills',
    what: 'Moves GitHub issues through a state machine. Checks for duplicates and past rejections, reproduces the claim, grills if needed, writes an agent brief.',
    when: '"What needs my attention?", "Let\'s look at #42".',
    io: 'State labels + AI-disclaimer comments on issues. Rejected enhancements go to .out-of-scope/.', calls: ['grilling', 'domain-modeling'] },
  'wait-what': { stage: 'session', who: 'you', src: 'mattpocock/skills',
    what: 'Re-pitches the last message with the missing context, in plain English and glossary terms.',
    when: 'The moment a reply does not land.', io: 'Conversation only.', calls: [] },

  'to-spec': { stage: 'plan', who: 'you', src: 'mattpocock/skills',
    what: 'Turns the conversation into a spec issue with no further interview: problem, solution, a long list of user stories, implementation and testing decisions. Confirms test seams with you first.',
    when: 'Right after grilling a big change.', io: 'GitHub issue labelled ready-for-agent.', calls: [] },
  'to-tickets': { stage: 'plan', who: 'you', src: 'mattpocock/skills',
    what: 'Splits a spec into tracer-bullet vertical slices (schema, API and UI in each), with blocking edges. Quizzes you on granularity first. Wide refactors are sequenced expand, migrate, contract.',
    when: 'After to-spec, or on any plan.', io: 'GitHub sub-issues with native blocked-by links, labelled ready-for-agent.', calls: [] },
  'wayfinder': { stage: 'plan', who: 'you', src: 'mattpocock/skills',
    what: 'For work bigger than one session. A map issue of decision tickets (research, prototype, grilling, task) plus a fog of war. Resolves one ticket per session until the way is clear.',
    when: 'Many open decisions, multi-week effort.', io: 'wayfinder:map issue + wayfinder:&lt;type&gt; child issues.', calls: ['grilling', 'domain-modeling', 'research', 'prototype'] },
  'research': { stage: 'plan', who: 'agent', src: 'mattpocock/skills',
    what: 'A background agent reads primary sources and writes a cited Markdown note.',
    when: 'A decision waits on an outside fact (docs, a third-party API).', io: 'One Markdown file, every claim cited.', calls: [] },

  'how': { stage: 'understand', who: 'you', src: 'pstack, adapted',
    what: 'Subsystem walkthrough. 2 to 4 parallel explorers, then one explainer (a single pass for simple questions). Sections: Overview, Key Concepts, How It Works, Where Things Live, Gotchas.',
    when: 'Before changing anything you have not traced.', io: 'Read-only. Flags wrong AGENTS.md claims in Gotchas.', calls: [] },
  'why': { stage: 'understand', who: 'you', src: 'pstack, adapted',
    what: 'Cited design rationale. Parallel investigators over git and PRs, GitHub issues, and repo docs (plus any connected MCP), then a synthesizer that separates known, inferred, and unknown.',
    when: '"Why is it like this?", regressions, before undoing a choice.', io: 'Read-only. Ends with Preserve / Change / Avoid / Risk when a change follows.', calls: ['how'] },
  'architect': { stage: 'understand', who: 'you', src: 'pstack, adapted',
    what: 'Design before code. Ground with how/why, 3 candidate designs under different constraints, screen against red flags, synthesize, implement against the sketch, scrap it if friction repeats.',
    when: 'A change crosses a function or package boundary.', io: 'Type sketch + rationale (usage first, alternatives, tradeoffs).', calls: ['how', 'why', 'codebase-design'] },
  'codebase-design': { stage: 'understand', who: 'agent', src: 'mattpocock/skills',
    what: 'Shared vocabulary for deep modules: module, interface, depth, seam, adapter, leverage, locality. The deletion test. Design it twice.',
    when: 'Whenever interface shape is the question.', io: 'Reference only.', calls: [] },
  'improve-codebase-architecture': { stage: 'understand', who: 'you', src: 'mattpocock/skills',
    what: 'Surveys the code for deepening opportunities, presents them as an HTML report, then grills through the one you pick.',
    when: 'Every few days, or before a big refactor.', io: 'HTML report in $TMPDIR, then glossary/ADR edits.', calls: ['codebase-design', 'grilling', 'domain-modeling'] },
  'prototype': { stage: 'understand', who: 'agent', src: 'mattpocock/skills',
    what: 'Throwaway code that answers one question. Logic: a single HTML state-machine demo. UI: several variants on one route, switched with ?variant=.',
    when: 'A question can be settled by watching it run. "Observe, don\'t ask."', io: 'Throwaway branch, verdict recorded on the issue.', calls: [] },

  'implement': { stage: 'build', who: 'you', src: 'mattpocock/skills',
    what: 'Builds one spec or ticket on the current branch. tdd at agreed seams, typecheck often, code-review at the end, commit.',
    when: 'One ticket, one branch.', io: 'Commits on the current branch.', calls: ['tdd', 'code-review'] },
  'implement-spec': { stage: 'build', who: 'you', src: 'mattpocock/skills',
    what: 'A whole spec on one integration branch. Treats the tickets as a graph, runs parallel implementer subagents in worktrees on the ready frontier, merges each, then code-review.',
    when: 'A spec with many independent tickets.', io: 'Integration branch + PR closing the spec and tickets.', calls: ['tdd', 'code-review'] },
  'tdd': { stage: 'build', who: 'agent', src: 'mattpocock/skills + pstack escape',
    what: 'Red then green, one vertical slice at a time, at seams agreed with you. No runner in the package? Use an executable check (curl, SQL, browser) red before, green after.',
    when: 'Features and bugs with a cheap seam.', io: 'A test next to the code, where docs/agents/verify.md lists a runner.', calls: ['codebase-design'] },
  'diagnosing-bugs': { stage: 'build', who: 'agent', src: 'mattpocock/skills',
    what: '6 gated phases: a feedback loop that goes red, reproduce + minimise, hypothesise, instrument, fix + regression test, cleanup.',
    when: 'Anything broken, throwing, flaky, or slow.', io: 'A red-then-green check for the PR.', calls: [] },
  'wizard': { stage: 'build', who: 'agent', src: 'mattpocock/skills',
    what: 'Generates an interactive bash script that walks a human through steps only they can do: dashboards, secrets, cutovers.',
    when: 'Setup the agent cannot do itself.', io: 'A bash script (ephemeral unless you keep it).', calls: [] },

  'code-review': { stage: 'ship', who: 'agent', src: 'mattpocock/skills + pstack triage',
    what: 'Two parallel reviewers. Standards: AGENTS.md rules plus Fowler smells. Spec: the GitHub issue. The lead then sorts findings into Act on, Consider, Noted, and Dismissed.',
    when: 'Before every PR. Every Act on gets fixed.', io: 'Report. Consider items go into the PR body.', calls: [] },
  'pr': { stage: 'ship', who: 'agent', src: 'mattpocock/skills + pstack process',
    what: 'Branch off main, small ordered commits, review first, Conventional Commits title, open ready (never draft). Body: Summary visual, Scope, Evidence before/after, Merge Danger.',
    when: 'Opening any PR or writing a commit message.', io: 'gh pr create. Squash-merge makes the title the commit.', calls: ['code-review'] },

  'handoff': { stage: 'session', who: 'you', src: 'mattpocock/skills + pstack pause/pickup',
    what: 'Pause: stop at a safe boundary, make a wip: commit, write a handoff doc. Resume: read the trail, name the resume point, route to a playbook, re-verify inherited claims.',
    when: 'Stepping away, context filling up, picking up someone\'s branch.', io: 'Handoff doc in $TMPDIR, wip commit.', calls: ['almalgo-mode'] },
  'retro': { stage: 'session', who: 'you', src: 'mattpocock/skills, adapted',
    what: 'Ranks improvements to the agent environment after a session (checks, AGENTS.md, skills, tooling), then applies the ones you accept, including the guide rebuild.',
    when: 'After a session that hurt.', io: 'Lint rules, AGENTS.md lines, skill edits.', calls: ['writing-for-agents'] },
  'writing-for-agents': { stage: 'session', who: 'agent', src: 'mattpocock/skills',
    what: 'How to write skills and AGENTS.md so agents actually follow them. Here, every skill change also rebuilds this guide.',
    when: 'Editing anything in .agents/skills/ or AGENTS.md.', io: 'Reference only.', calls: [] },
};

// file: the playbook under almalgo-mode/playbooks/. check.mjs requires one entry per file and
// at least as many steps as the file has top-level numbered steps. Optional 3rd item = sub-heading.
window.PLAYBOOKS = [
  { id: 'investigation', file: 'investigation.md', name: 'Investigation', own: 'You own the answer. Read-only.', when: 'How does X work, why is Y like this, should we do A or B?', steps: [
    ['Walk the subsystem; add why for "why is it like this"', ['how', 'why']],
    ['Answer as Overview / Concepts / How / Where / Gotchas, or a tradeoffs table for a decision', []],
    ['Behavior you could observe? Run it rather than reason about it (the runtime rungs)', []],
    ['A wrong AGENTS.md or GLOSSARY.md claim? Say so and offer the one-line fix', []],
  ], out: 'A cited answer. No PR, no architect. Turns into a code change? Re-route to Bug fix or Feature.' },
  { id: 'bug', file: 'bug-fix.md', name: 'Bug fix', own: 'Every shipped line traces to runtime evidence. A "might help" change does not ship.', when: 'Broken, throwing, wrong, or flaky.', steps: [
    ['Build a feedback loop that goes RED on this bug, on the surface it shows up on. Drive it yourself', ['diagnosing-bugs']],
    ['Seed hypotheses from the subsystem and its history; eliminate them with runtime evidence', ['how', 'why']],
    ['Plan the fix at the root cause; architect if it crosses a boundary', ['architect']],
    ['Runner + cheap seam: commit the failing test before the fix. Otherwise keep the red check', ['tdd']],
    ['Same surface: the original repro passes. Then the rest of the verify ladder', []],
    ['Review against main, fix every Act on, PR with Closes #N', ['code-review', 'pr']],
  ], out: 'What was broken, root cause, fix, red-then-green output pasted verbatim.' },
  { id: 'feature', file: 'feature.md', name: 'Feature', own: 'You own the design. Plan, delegate, review, verify.', when: 'New or changed behavior.', steps: [
    ['Confirm alignment: a ready-for-agent issue or ticket. "Done" unclear? Grill first', ['grill-with-docs']],
    ['Walk every subsystem the feature touches', ['how']],
    ['Name the data shape: types, tables, API/contract shapes, access patterns. Schema? Read the data layer\'s AGENTS.md', []],
    ['Signatures cross a boundary? Sketch first; a large sketch ships as its own commit', ['architect', 'codebase-design']],
    ['Throughput checkpoint: blocking steps, independent streams, shared state, smallest decomposition', []],
    ['Delegate to almalgo-agent subagents with a precise scope; tdd at agreed seams; review every diff', ['tdd']],
    ['Verify on the matching surface. Inconclusive or wrong surface is not a pass', []],
    ['Small ordered commits: schema, then backend, then UI. Large? Stacked PRs', []],
    ['Review against the issue (Spec axis), fix every Act on, open the PR', ['code-review', 'pr']],
  ], out: 'What was built and for whom, choices (table), checkpoint, evidence, open decisions.' },
  { id: 'refactor', file: 'refactoring.md', name: 'Refactoring', own: 'The structure changes; the behavior does not. Found a bug? Split it out.', when: 'Rename, extract, inline, dedupe, move.', steps: [
    ['Pin current behavior first: a test, recorded request/script/DB output, or screenshots. Typecheck is not a pin', ['how']],
    ['Name the target shape. It must delete branches or layers, not add indirection', ['architect']],
    ['Subtract first: dead code, one-caller wrappers, redundant validation, orphan references', []],
    ['Small steps, pin stays green. Migrate every caller and delete the old API together. Grep renames everywhere', []],
    ['Re-run the pin and diff it against step 1, plus the verify ladder', []],
    ['Not easier to read? Revert it', []],
    ['Commits: subtraction, reshape, follow-ups. Review, then PR', ['code-review', 'pr']],
  ], out: 'Structure changed, the pin, equivalence evidence, reader-load gain, what was reverted.' },
  { id: 'perf', file: 'perf.md', name: 'Perf', own: 'You own the measurement story. Never claim a speedup from reading code.', when: 'Something measured is slow. One-off fix or sustained hillclimb.', steps: [
    ['Baseline on a realistic workload: EXPLAIN (ANALYZE, BUFFERS), median of N curl timings, browser timings. Rule out cache, timeouts, errors', [], 'One-off fix'],
    ['Hypotheses, cheapest first: don\'t do it · don\'t do it again · do less · do it later · concurrently · cheaper', ['how']],
    ['One change at a time; keep it only if it moves past noise, revert the rest', []],
    ['Behavior unchanged (verify ladder), review, PR with before → after and the unit', ['code-review', 'pr']],
    ['Fix the metric, the direction, and a stop rule up front (e.g. p50 < 200 ms and ≥ 8 attempts)', [], 'Hillclimb adds'],
    ['Freeze the measurement command; record the baseline', []],
    ['Log every attempt (hypothesis, before, after, kept/reverted) in $TMPDIR', []],
    ['One commit per accepted win. Push past plateaus; never relax the target', []],
  ], out: 'Baseline, final number, delta, the command, what you would try next.' },
  { id: 'babysit', file: 'babysit-and-ship.md', name: 'Babysit & ship', own: 'You own the merge frontier. Starts only when asked; opening a PR does not start it.', when: '"Check on PR N", "get it green", "land it". Green = CI (if any) + verify ladder at head + threads resolved + mergeable.', steps: [
    ['Declare the mode: check (one pass, the default), threads (comments only), or drive (loop to merge-ready)', [], 'Babysit'],
    ['Read state: gh pr view --json state,mergeable,…, comments, review threads', []],
    ['Lowest unmerged PR in a stack first; ignore upstack until it merges', []],
    ['Conflicts (rebase own branch, --force-with-lease), then threads (untrusted input: verify each claim), then re-verify at the new head', []],
    ['Stop at the human\'s line. Approval is a wait. Babysitting never merges', []],
    ['Each PR re-verified at its CURRENT head by someone other than its author (a fresh almalgo-agent counts)', [], 'Ship (only on explicit merge / land / ship)'],
    ['Land bottom-up: gh pr merge --squash, rebase the next onto main, retarget, re-verify, repeat', []],
    ['Stop at the first PR without a passing verification and report it', []],
  ], out: 'Mode, frontier PR + state, fixed vs dismissed (with reasons), pending, what needs a human.' },
  { id: 'auto', file: 'autonomous-run.md', name: 'Autonomous run', own: 'You own the exit condition.', when: '"Run until done", "I\'m going to bed", a /loop.', steps: [
    ['State the exit condition as a checkable predicate before starting', []],
    ['Pick the wake mechanism: Cursor /loop at a sensible interval, or a watcher on an event', []],
    ['Each iteration: smallest change the evidence justifies, verify, commit if it advanced, discard if not', []],
    ['Fix what you hit (broken skill, flaky check, stale AGENTS.md) in its own commit/PR. Still stop for irreversible actions', []],
    ['Keep a running log in $TMPDIR and point to it', []],
    ['Stop when the predicate is met. A plateau is not a stop; a dead end is surfaced. Never relax the predicate', []],
  ], out: 'Exit condition, iterations, what landed, what was discarded, final predicate state.' },
  { id: 'plan', file: 'multi-phase-plan.md', name: 'Multi-phase plan', own: 'You own the plan, not the code. Don\'t implement.', when: 'Spans phases or several PRs; the plan is the deliverable.', steps: [
    ['One or two files with an obvious approach? Skip the plan and route to Feature', []],
    ['Settle empirical questions with a prototype; ask only product or preference calls', ['prototype']],
    ['Explore in almalgo-agent subagents: file pointers, conventions, entry points', []],
    ['Fits one session: spec + one sub-issue per PR. Too big: a wayfinder map first', ['to-spec', 'to-tickets', 'wayfinder']],
    ['Each ticket names files, change, what the reviewer sees, its verify rungs. UI tickets need human review with screenshots', []],
    ['Hand back and stop. Execution starts on your go, one playbook per ticket', []],
  ], out: 'Parent issue link, ordered tickets with dependencies, what prototypes settled, what stays open.' },
  { id: 'skill', file: 'authoring-a-skill.md', name: 'Authoring a skill', own: 'You own the skill\'s voice. When in doubt, delete.', when: 'Anything in .agents/skills/ (and the guide that documents it).', steps: [
    ['Follow the writing guide', ['writing-for-agents']],
    ['Frontmatter: name = folder, description = what + when; disable-model-invocation for skills you type', []],
    ['Keep SKILL.md short; reference material in sibling files; delegate to other skills by name', []],
    ['node .agents/skills/check.mjs, then spot-check every command by running it', []],
    ['Update the skill map, README, AND the loop guide (data.js or docs/agents/guide.js), then bash .agents/loop-guide/build.sh', []],
    ['Try it once on a real task; note the result in the PR Evidence', []],
    ['PR with scope skills, PDF and stamp included', ['pr']],
  ], out: 'What the skill does, key decisions, the trial run.' },
];

// Overridden by docs/agents/guide.js.
window.VERIFY = { rungs: [], changes: [] };

window.PRINCIPLES = [
  ['Core', [
    ['Laziness', 'Delete, stdlib, platform, existing dep, then the smallest new code.'],
    ['Data shape first', 'Name types and structures before logic. Constraint over conditional.'],
    ['Subtract before you add', 'Clear dead weight, then build on the simpler base.'],
    ['Redesign, don\'t bolt on', 'Before a first release, a clean shape costs least.'],
    ['Attack the premise', 'Two fixes on one assumption failed? Question the assumption.'],
  ]],
  ['Architecture', [
    ['Boundary discipline', 'Validate requests, webhooks, env, external APIs. Trust types inside.'],
    ['Type discipline', 'Illegal states unrepresentable. Parse at the edge; derive types from the schema.'],
    ['Idempotent operations', 'Imports, migrations, jobs, webhooks converge when run twice.'],
    ['Migrate callers, then delete', 'Move every caller and remove the old API in one change.'],
  ]],
  ['Verification', [
    ['Prove it works', 'The real artifact, not "it compiles" or a subagent\'s say-so.'],
    ['Fix root causes', 'Reproduce, ask why until the cause. No silencing guards.'],
    ['Small verifiable units', 'Each step ends green. History proves itself.'],
    ['Test behavior, not implementation', 'Assert literal values through the public interface.'],
    ['Explain the number', 'Know what limits a measurement before reporting it.'],
  ]],
  ['Delegation & meta', [
    ['Guard the context window', 'Bulk reading goes to subagents, summaries stay.'],
    ['Observe, don\'t ask', 'If running something settles it, prototype it.'],
    ['Encode lessons in structure', 'Second time you write a rule, make it a check.'],
  ]],
];

window.FLOWS = [
  { id: 'big', name: 'Big feature', blurb: 'Ambiguous or cross-package work. Align first, then the loop runs once per ticket.', nodes: [
    ['you', '/grill-with-docs', 'Interview in rounds. GLOSSARY.md + ADRs updated live.'],
    ['you', '/to-spec', 'Conversation becomes a GitHub spec issue, ready-for-agent.'],
    ['gh', 'Spec issue', 'Problem, solution, user stories, decisions, test seams.'],
    ['you', '/to-tickets', 'Vertical slices with blocking edges. You approve granularity.'],
    ['gh', 'Sub-issues', 'Native blocked-by links. The frontier is visible in GitHub.'],
    ['agent', '/almalgo-mode × ticket', 'Feature playbook per ticket, or /implement-spec in parallel.'],
    ['stack', 'Verify ladder', 'docs/agents/verify.md rungs for what the diff touches.'],
    ['agent', 'code-review → pr', 'Fix every Act on. Open ready, Closes #N.'],
    ['you', 'Babysit / ship', 'Only on your ask. Merge is always yours.'],
  ] },
  { id: 'bug', name: 'Bug fix', blurb: 'Small and clear: straight into almalgo-mode. Evidence before every line.', nodes: [
    ['gh', 'Issue #N', 'Labelled ready-for-agent, or you describe it.'],
    ['you', '/almalgo-mode', 'Sized small, so it picks the Bug fix playbook.'],
    ['agent', 'diagnosing-bugs', 'A loop that goes RED on this bug, on its surface.'],
    ['agent', 'how · why', 'Hypotheses from the subsystem and its history.'],
    ['agent', 'Root-cause fix', 'architect if it crosses a boundary.'],
    ['agent', 'tdd or red check', 'Runner + cheap seam: failing test commit, then fix. Else keep the red check.'],
    ['stack', 'Repro → GREEN', 'Same surface, plus the verify ladder.'],
    ['agent', 'code-review → pr', 'Red-then-green output pasted in Evidence.'],
  ] },
  { id: 'parallel', name: 'Parallel spec', blurb: '/implement-spec: tickets as a graph, the frontier built concurrently.', nodes: [
    ['agent', 'Integration branch', 'One branch for the whole spec.'],
    ['gh', 'Ready frontier', 'Open tickets with no open blockers.'],
    ['agent', 'Implementers ×N', 'One subagent per ticket, own worktree, tdd.'],
    ['agent', 'Merger', 'Merges each finished ticket into the integration branch.'],
    ['gh', 'New frontier', 'Unblocked tickets start immediately.'],
    ['agent', 'code-review', 'Once, on the integration branch. One fixer subagent.'],
    ['agent', 'PR', 'Closes the spec and every ticket.'],
  ] },
  { id: 'triage', name: 'Triage', blurb: 'Incoming issues become agent-ready briefs or get closed with a reason.', nodes: [
    ['gh', 'New issue', 'Unlabeled.'],
    ['you', '/triage', '"What needs my attention?"'],
    ['agent', 'Gather + dedupe', 'Already implemented? Previously rejected (.out-of-scope)?'],
    ['agent', 'Recommend', 'Category + state, with reasoning. Waits for you.'],
    ['stack', 'Verify the claim', 'Reproduce the bug from the reporter\'s steps.'],
    ['agent', 'Grill if needed', 'grilling + domain-modeling.'],
    ['gh', 'Outcome', 'Agent brief, needs-info notes, or close.'],
  ] },
  { id: 'wayfinder', name: 'Wayfinder', blurb: 'Too big for one session. Decisions first, implementation later.', nodes: [
    ['you', '/wayfinder idea', 'Grill to name the destination.'],
    ['gh', 'Map issue', 'Destination, decisions so far, fog of war.'],
    ['gh', 'Decision tickets', 'research · prototype · grilling · task, with blockers.'],
    ['agent', 'Research ×N', 'AFK, in parallel, on throwaway branches.'],
    ['you', 'One ticket / session', 'Claim, resolve, close, record on the map.'],
    ['gh', 'Fog graduates', 'New tickets as the view clears.'],
    ['you', '→ /to-spec', 'Way is clear: spec and tickets, then build.'],
  ] },
  { id: 'session', name: 'Pause & improve', blurb: 'Keeping work resumable and the environment getting better.', nodes: [
    ['you', '/handoff', 'Safe boundary, wip: commit, doc in $TMPDIR.'],
    ['agent', 'Next session', 'Reads the trail, does not redo work.'],
    ['agent', 'Route + re-verify', 'Back into an almalgo-mode playbook.'],
    ['you', '/retro', 'What cost time? Ranked, with exact edits.'],
    ['agent', 'Encode it', 'Lint rule > AGENTS.md line > skill edit.'],
    ['gh', 'PR', 'Skills are code. Next session starts smarter.'],
  ] },
];

window.QUICKSTART = [
  ['Install once per repo', 'curl the kit\'s install.sh (or clone + run it), then /setup-almalgo-mode. It writes docs/agents/ and the verify ladder.'],
  ['Open the session', 'In Cursor, type /almalgo-mode and press Alt+Enter (Option+Enter on Mac). It stays on for the whole chat.'],
  ['Say what you want', 'Paste the issue number or describe the task. The agent sizes it and picks a playbook.'],
  ['Big or fuzzy?', 'Start with /grill-with-docs instead. Answer its rounds, then /to-spec and /to-tickets.'],
  ['Watch the todo list', 'The playbook steps appear verbatim. A skipped step shows "skip: reason".'],
  ['Read the evidence', 'Every claim comes with the command that proved it, or a label: inferred or guess.'],
  ['You merge', 'The agent opens a ready PR. Babysitting and merging happen only when you ask.'],
];

window.ISSUE_STATES = [
  ['needs-triage', 'Maintainer needs to evaluate', '#a0aec0'],
  ['needs-info', 'Waiting on the reporter', '#f5b84b'],
  ['ready-for-agent', 'Fully specified, an agent can take it', '#68d391'],
  ['ready-for-human', 'Needs a person (judgement, access, manual testing)', '#7aa2ff'],
  ['wontfix', 'Closed with a reason; rejected enhancements go to .out-of-scope/', '#fc8181'],
];

window.REPO_CONFIG = [
  ['AGENTS.md', 'Root cheat sheet + pointer to the skills. Area AGENTS.md files hold package detail.'],
  ['GLOSSARY.md', 'Domain terms, created lazily by domain-modeling.'],
  ['docs/adr/', 'Decisions that are hard to reverse, surprising, and a real trade-off.'],
  ['docs/agents/issue-tracker.md', 'GitHub via gh: sub-issues, native blocked-by, area/type/priority labels.'],
  ['docs/agents/triage-labels.md', 'The 5 state labels the skills apply.'],
  ['docs/agents/domain.md', 'Glossary + ADR layout and how to use them.'],
  ['docs/agents/verify.md', 'This project\'s verify ladder: real commands, which rungs per change, merge-danger checklist.'],
  ['docs/agents/guide.js', 'Project name + verify ladder for this guide.'],
  ['.cursor/agents/almalgo-agent.md', 'The subagent every playbook delegates to. model: inherit.'],
];

window.KEEP_IN_SYNC = [
  'Any change under .agents/ (a skill, playbook, principle) also updates .agents/loop-guide/data.js; a change to docs/agents/verify.md also updates docs/agents/guide.js.',
  'Then run bash .agents/loop-guide/build.sh: it rebuilds .agents/agentic-loop-guide.pdf and its stamp.',
  'node .agents/skills/check.mjs fails if a skill, playbook, principle or rung is missing from the guide, setup TODOs remain, or the PDF is older than its sources.',
  'Commit the source edit, the guide data, the PDF, and the stamp together.',
];
